### ISSUE TITLE
feat: improve user experience on mobile

### ISSUE THREAD

**Issue by friedrith** [friedrith/cookbook#38]
Login on mobile is painful :

- app opened in-browser apps make it hard to find it again and loose the authentication
- app installed require to log-in again on iOS

## Tasks

- [ ] force open in the browser (not in-browser app)
- [ ] find a way to keep login when installing the app on iOS
- [ ] improve settings on mobile
- [ ] open PWA from website (https://developer.chrome.com/docs/web-platform/launch-handler/) (for login in app and share)

bonus:
- [ ] propose to install app from beginning 
- [ ] improve login from PWA
